# Generated by Django 5.0.2 on 2025-12-04 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0005_alter_administradores_update_alter_alumnos_update_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAcademico',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('Conferencia', 'Conferencia'), ('Taller', 'Taller'), ('Seminario', 'Seminario'), ('Concurso', 'Concurso')], max_length=50)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('lugar', models.CharField(max_length=255)),
                ('publico_objetivo', models.TextField(help_text='Lista JSON de públicos objetivo')),
                ('programa_educativo', models.CharField(blank=True, choices=[('Ingenieria en Ciencias de la Computacion', 'Ingenieria en Ciencias de la Computacion'), ('Licenciatura en Ciencias de la Computacion', 'Licenciatura en Ciencias de la Computacion'), ('Ingenieria en Tecnologias de la Informacion', 'Ingenieria en Tecnologias de la Informacion')], max_length=100, null=True)),
                ('descripcion', models.TextField()),
                ('cupo_maximo', models.PositiveSmallIntegerField()),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_responsable', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
